apiVersion: v1
kind: Pod
metadata:
  name: liveliness-probe-demo
  labels:
    app: liveliness-probe-demo
spec:
  containers:
  - name: liveliness-probe-demo
    image: k8s.gcr.io/busybox
    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 10