apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers: 
  - name: count
    image: busybox:1.28
    command: ["sh", "-c", "i=0; while true; do echo $i; i=$((i+1)); sleep 1; done"]