apiVersion: v1
kind: Pod
metadata:
  name: issue-pod
  labels:
    app: demo
spec:
  containers:
  - name: container1
    image: docker.io/openshift
    ports:
    - containerPort: 80
    