apiVersion: v1
kind: Pod
metadata:
  name: multi-container-storage
spec:
  containers:
  - name: container1
    image: centos:7
    command:
    - "bin/bash"
    - "-c"
    - "sleep 10000"
    volumeMounts:
    - name: container-volume
      mountPath: /tmp/data
  - name: container2
    image: centos:7
    command:
    - "bin/bash" 
    - "-c"
    - "sleep 10000"
    volumeMounts:
    - name: container-volume
      mountPath: /tmp/data
  volumes:
  - name: container-volume
    emptyDir: {}